openapi: 3.0.0
info:
  title: Musement
  version: 1.0.0
paths:
  /api/3/cities:
    get:
      tags:
        - city
      summary: Get cities
      responses:
        200:
          description: OK response
  /api/3/cities/{id}:
    get:
      tags:
        - city
      summary: Get city
      parameters:
        - name: id
          in: path
          description: ID of city
          required: true
          explode: false
          schema:
            type: integer
      responses:
        200:
          description: OK response
  /api/3/cities/{id}/forecast:
    get:
      tags:
        - forecast
        - city
      summary: Get forecast for city
      parameters:
        - name: id
          in: path
          description: ID of city
          required: true
          schema:
            type: integer
        - name: day
          in: query
          description: The number of next day of forecast, default 0(today)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
            maximum: 14
          explode: true
      responses:
        200:
          description: OK response
          content:
            application/json:
              schema:
                type: string
                example: 'Forecast for selected day  is Sunny'
        500:
          description: Fatal error
    put:
      tags:
        - city
        - forecast
      summary: Set forecast for city
      parameters:
        - name: id
          in: path
          description: ID of city
          required: true
          schema:
            type: integer
      requestBody:
        description: Forecast information request body
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
              example:
                day 1: 'Sunny'
                day 2: 'Cloudly'
      responses:
        201:
          description: OK response
        400:
          description: Validation error
        401:
          description: Unauthorized
        403:
          description: Forbbiden
        500:
          description: Fatal error
