name: Test

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    env:
      FONT_AWESOME_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_AUTH_TOKEN }}
      TC_NPM_REGISTRY_ACCESS_TOKEN: ${{ secrets.TC_NPM_REGISTRY_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "działa"

